#!/usr/bin/env python3
"""
16_make_html_summary_report.py
==============================
Creates a tabbed, manuscript-style HTML summary report for LAB-Score v1.1.
This complements the full interactive strain-level report generated by
12_interactive_report.py.
"""

import argparse
from pathlib import Path
import html
import pandas as pd

ap = argparse.ArgumentParser(description="Create LAB-Score v1.1 tabbed HTML summary report")
ap.add_argument("--pipeline-outdir", required=True, help="Pipeline output directory, e.g. lab_score_out")
ap.add_argument("--outdir", required=True, help="Output directory for HTML report")
ap.add_argument("--title", default="LAB-Score v1.1 Summary Report")
args = ap.parse_args()

base = Path(args.pipeline_outdir)
outdir = Path(args.outdir)
outdir.mkdir(parents=True, exist_ok=True)
out_html = outdir / "LAB_SCORE_v1_1_summary_report.html"

# ---------- helpers ----------
def read_tsv(rel):
    p = base / rel
    if not p.exists():
        return None
    try:
        return pd.read_csv(p, sep="\t")
    except Exception:
        return None

def safe_count(df, col, value):
    if df is None or col not in df.columns:
        return "NA"
    return int((df[col].astype(str) == value).sum())

def table_html(df, max_rows=30):
    if df is None:
        return "<p class='missing'>Table not found.</p>"
    show = df.head(max_rows).copy()
    for c in show.columns:
        if pd.api.types.is_float_dtype(show[c]):
            show[c] = show[c].map(lambda x: "" if pd.isna(x) else f"{x:.3f}")
    return show.to_html(index=False, classes="data-table", border=0, escape=False)

def fig_html(title, rel):
    p = base / rel
    if not p.exists():
        return f"<div class='figure-card missing'><h4>{html.escape(title)}</h4><p>Missing: {html.escape(str(p))}</p></div>"
    # report lives in OUTDIR, usually base/16_html_report, so ../rel works
    src = "../" + rel
    return f"""
    <div class='figure-card'>
      <h4>{html.escape(title)}</h4>
      <img src='{html.escape(src)}' alt='{html.escape(title)}'>
    </div>
    """

def path_status(rel):
    p = base / rel
    status = "✅" if p.exists() else "❌"
    return f"{status} <code>{html.escape(rel)}</code>"

scores = read_tsv("09_scores/LAB_score_v1.tsv")
species = read_tsv("09_scores/species_mean_scores.tsv")
priority = read_tsv("09_scores/priority_class_counts.tsv")
top100 = read_tsv("09_scores/top100_candidates.tsv")
ml_perf = read_tsv("10_ml/model_performance_summary.tsv")
ml_feat = read_tsv("10_ml/RF_classification_functional_feature_importance.tsv")
sensitivity = read_tsv("13_sensitivity/weight_sensitivity_summary.tsv")
baselines = read_tsv("14_baselines/baseline_comparison_summary.tsv")
manifest = read_tsv("15_release/LAB_SCORE_v1_1_release_manifest.tsv")

n = len(scores) if scores is not None else "NA"
elite = safe_count(scores, "Candidate_tier_v1_1", "Elite candidate")
high = safe_count(scores, "Candidate_tier_v1_1", "High candidate")
critical = safe_count(scores, "Candidate_tier_v1_1", "Critical safety review")

# Safety status naming can be Pass/Caution/Critical or manuscript phrases.
if scores is not None and "Refined_safety_status" in scores.columns:
    st = scores["Refined_safety_status"].astype(str)
    caution = int(((st == "Caution") | (st == "Cautionary safety review")).sum())
    pass_n = int(((st == "Pass") | (st == "No safety marker detected")).sum())
else:
    caution = pass_n = "NA"

# ML metric cards
func_r2 = "NA"
func_acc = "NA"
if ml_perf is not None and {"Model", "Metric", "Value"}.issubset(ml_perf.columns):
    try:
        func_r2 = float(ml_perf[(ml_perf["Model"] == "RF_Regression_FUNC") & (ml_perf["Metric"] == "R2")]["Value"].iloc[0])
        func_r2 = f"{func_r2:.3f}"
    except Exception:
        pass
    try:
        func_acc = float(ml_perf[(ml_perf["Model"] == "RF_Class_FUNC") & (ml_perf["Metric"] == "Accuracy")]["Value"].iloc[0])
        func_acc = f"{func_acc:.3f}"
    except Exception:
        pass

figs = [
    ("Figure 2. LAB-Score distribution", "11_figures/fig2_score_distribution.png"),
    ("Figure 3. Refined candidate tiers", "11_figures/fig3_candidate_tiers.png"),
    ("Figure 4. Species summary", "11_figures/fig4_species_summary.png"),
    ("Figure 5. ML feature importance", "11_figures/fig5_ml_feature_importance.png"),
    ("ML actual vs predicted", "10_ml/fig_ml_actual_vs_predicted.png"),
    ("ML confusion matrix", "10_ml/fig_ml_confusion_matrix.png"),
]

html_text = f"""<!doctype html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<title>{html.escape(args.title)}</title>
<style>
:root {{
  --navy:#12355b; --blue:#2374ab; --teal:#1b998b; --orange:#f2a541;
  --red:#c94c4c; --bg:#f6f8fb; --card:#fff; --text:#1f2933;
  --muted:#637381; --border:#d9e2ec;
}}
body {{ margin:0; font-family:Arial, Helvetica, sans-serif; background:var(--bg); color:var(--text); }}
header {{ background:linear-gradient(135deg,var(--navy),var(--blue),var(--teal)); color:white; padding:34px 46px; }}
header h1 {{ margin:0; font-size:34px; }}
header p {{ margin:8px 0 0 0; font-size:16px; opacity:.95; }}
.container {{ padding:24px 42px 50px 42px; }}
.metrics {{ display:grid; grid-template-columns:repeat(6,1fr); gap:14px; margin-bottom:22px; }}
.metric-card {{ background:var(--card); border:1px solid var(--border); border-radius:14px; padding:16px; box-shadow:0 2px 6px rgba(0,0,0,.05); }}
.metric-label {{ color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.7px; }}
.metric-value {{ font-size:28px; font-weight:700; margin-top:7px; color:var(--navy); }}
.tabs {{ display:flex; flex-wrap:wrap; gap:8px; margin-bottom:18px; }}
.tab-button {{ border:1px solid var(--border); background:white; color:var(--navy); padding:12px 15px; border-radius:999px; cursor:pointer; font-weight:600; }}
.tab-button.active {{ background:var(--navy); color:white; }}
.tab-content {{ display:none; background:white; border-radius:16px; border:1px solid var(--border); padding:24px; box-shadow:0 2px 8px rgba(0,0,0,.05); }}
.tab-content.active {{ display:block; }}
h2,h3 {{ color:var(--navy); }} h2 {{ margin-top:0; }}
.note {{ background:#eef7ff; border-left:5px solid var(--blue); padding:14px 16px; border-radius:10px; margin:14px 0 20px 0; }}
.warning {{ background:#fff7e6; border-left:5px solid var(--orange); padding:14px 16px; border-radius:10px; margin:14px 0 20px 0; }}
.data-table {{ width:100%; border-collapse:collapse; margin-top:14px; font-size:13px; }}
.data-table th {{ background:var(--navy); color:white; padding:10px; text-align:left; }}
.data-table td {{ border-bottom:1px solid var(--border); padding:8px 10px; }}
.data-table tr:nth-child(even) {{ background:#f9fbfd; }}
.figure-grid {{ display:grid; grid-template-columns:repeat(2,minmax(300px,1fr)); gap:18px; }}
.figure-card {{ background:#fff; border:1px solid var(--border); border-radius:14px; padding:14px; text-align:center; }}
.figure-card h4 {{ margin:4px 0 12px 0; color:var(--navy); }}
.figure-card img {{ max-width:100%; border-radius:8px; }}
.file-list li {{ margin-bottom:8px; }} code {{ background:#eef2f7; padding:3px 6px; border-radius:5px; }}
.missing {{ color:var(--red); font-weight:600; }}
footer {{ text-align:center; color:var(--muted); margin-top:30px; font-size:13px; }}
@media (max-width:1100px) {{ .metrics {{ grid-template-columns:repeat(2,1fr); }} .figure-grid {{ grid-template-columns:1fr; }} }}
</style>
</head>
<body>
<header>
  <h1>{html.escape(args.title)}</h1>
  <p>Genome-based, safety-aware prioritization report for lactic acid bacteria candidates</p>
</header>
<div class='container'>
  <div class='metrics'>
    <div class='metric-card'><div class='metric-label'>Genomes scored</div><div class='metric-value'>{n}</div></div>
    <div class='metric-card'><div class='metric-label'>Elite candidates</div><div class='metric-value'>{elite}</div></div>
    <div class='metric-card'><div class='metric-label'>High candidates</div><div class='metric-value'>{high}</div></div>
    <div class='metric-card'><div class='metric-label'>No safety marker / Pass</div><div class='metric-value'>{pass_n}</div></div>
    <div class='metric-card'><div class='metric-label'>Critical review</div><div class='metric-value'>{critical}</div></div>
    <div class='metric-card'><div class='metric-label'>Functional RF accuracy</div><div class='metric-value'>{func_acc}</div></div>
  </div>

  <div class='tabs'>
    <button class='tab-button active' onclick="openTab(event,'overview')">Overview</button>
    <button class='tab-button' onclick="openTab(event,'tiers')">Candidate tiers</button>
    <button class='tab-button' onclick="openTab(event,'top')">Top candidates</button>
    <button class='tab-button' onclick="openTab(event,'species')">Species summary</button>
    <button class='tab-button' onclick="openTab(event,'ml')">Functional drivers / ML</button>
    <button class='tab-button' onclick="openTab(event,'sensitivity')">Sensitivity</button>
    <button class='tab-button' onclick="openTab(event,'baseline')">Baselines</button>
    <button class='tab-button' onclick="openTab(event,'files')">Output files</button>
  </div>

  <section id='overview' class='tab-content active'>
    <h2>Overview</h2>
    <p>LAB-Score v1.1 integrates safety screening, gastrointestinal survival modules, probiotic-associated functions, and fermentation-related features into a continuous score and refined candidate tier.</p>
    <div class='note'><strong>Interpretation:</strong> LAB-Score is a decision-support framework for selecting candidate genomes for downstream experimental validation. It is not definitive proof of probiotic efficacy or safety.</div>
    <div class='figure-grid'>{''.join(fig_html(t,r) for t,r in figs[:4])}</div>
  </section>

  <section id='tiers' class='tab-content'>
    <h2>Candidate tiers</h2>
    <p>Counts of raw or refined LAB-Score candidate tiers.</p>
    {table_html(priority, 30)}
    <h3>Score table preview</h3>
    {table_html(scores, 25)}
  </section>

  <section id='top' class='tab-content'>
    <h2>Top non-critical candidates</h2>
    <p>Highest-ranking non-critical genomes for downstream validation.</p>
    {table_html(top100, 50)}
  </section>

  <section id='species' class='tab-content'>
    <h2>Species summary</h2>
    <p>Species-level aggregation of LAB-Score and candidate-tier structure.</p>
    {table_html(species, 60)}
  </section>

  <section id='ml' class='tab-content'>
    <h2>Functional drivers and ML interpretation</h2>
    <p>Random Forest models are used as an interpretation layer. Functional-only results are preferred for biological interpretation.</p>
    <h3>Model performance</h3>
    {table_html(ml_perf, 20)}
    <h3>Functional feature importance</h3>
    {table_html(ml_feat, 30)}
    <div class='figure-grid'>{''.join(fig_html(t,r) for t,r in figs[3:])}</div>
  </section>

  <section id='sensitivity' class='tab-content'>
    <h2>Weight sensitivity analysis</h2>
    <p>Alternative component-weight schemes test robustness of LAB-Score rankings.</p>
    {table_html(sensitivity, 30)}
  </section>

  <section id='baseline' class='tab-content'>
    <h2>Baseline comparison</h2>
    <p>Comparison with simplified single-component or reduced-component ranking strategies.</p>
    {table_html(baselines, 30)}
  </section>

  <section id='files' class='tab-content'>
    <h2>Output files</h2>
    <ul class='file-list'>
      <li>{path_status('09_scores/LAB_score_v1.tsv')}</li>
      <li>{path_status('09_scores/top100_candidates.tsv')}</li>
      <li>{path_status('09_scores/species_mean_scores.tsv')}</li>
      <li>{path_status('10_ml/model_performance_summary.tsv')}</li>
      <li>{path_status('13_sensitivity/weight_sensitivity_summary.tsv')}</li>
      <li>{path_status('14_baselines/baseline_comparison_summary.tsv')}</li>
      <li>{path_status('15_release/LAB_SCORE_v1_1_release_manifest.tsv')}</li>
      <li>{path_status('12_report/LAB_score_report.html')}</li>
    </ul>
    <h3>Release manifest preview</h3>
    {table_html(manifest, 50)}
  </section>
  <footer>Generated automatically by LAB-Score v1.1.</footer>
</div>
<script>
function openTab(evt, tabName) {{
  var tabcontent = document.getElementsByClassName('tab-content');
  for (var i=0; i<tabcontent.length; i++) tabcontent[i].classList.remove('active');
  var tabbuttons = document.getElementsByClassName('tab-button');
  for (var i=0; i<tabbuttons.length; i++) tabbuttons[i].classList.remove('active');
  document.getElementById(tabName).classList.add('active');
  evt.currentTarget.classList.add('active');
}}
</script>
</body>
</html>
"""

out_html.write_text(html_text, encoding="utf-8")
print("[html] Saved:", out_html)
